const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  username: state => state.user.username,
  info: state => state.user.info,
  center: state => sessionStorage.center || state.user.center,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permission_routes: state => state.permission.routes,
  menu_routes: state => state.permission.menuRoutes,
  sysArr: state => state.permission.sysArr,
  sysActive: state => state.permission.sysActive,
  errorLogs: state => state.errorLog.logs,
  org_list: state => state.organization.list,
  isAdSystem: state => state.permission.isAdSystem,
}
export default getters
